
SRCS =	system.c	\
	gadgets.c	\
	text.c		\
	sound.c		\
	joystick.c	\
	snapshot.c	\
	image.c		\
	random.c	\
	hash.c		\
	setup.c		\
	misc.c		\
	sdl.c		\
	zip/ioapi.c	\
	zip/iowin32.c	\
	zip/unzip.c	\
	zip/miniunz.c

OBJS =	system.o	\
	gadgets.o	\
	text.o		\
	sound.o		\
	snapshot.o	\
	joystick.o	\
	image.o		\
	random.o	\
	hash.o		\
	setup.o		\
	misc.o		\
	sdl.o		\
	zip/ioapi.o	\
	zip/iowin32.o	\
	zip/unzip.o	\
	zip/miniunz.o

LIBGAME = libgame.a
