
SRCS =	cave.c		\
	convert.c	\
	graphics.c	\
	init.c		\
	game.c		\
	logic.c		\
	reademc.c

OBJS =	cave.o		\
	convert.o	\
	graphics.o	\
	init.o		\
	game.o		\
	logic.o		\
	reademc.o

GAME_EM = game_em.a
