
.option norvc

#define RV_COMPLIANCE_RV32M
#define RV_COMPLIANCE_CODE_BEGIN
#define RVTEST_IO_INIT
#define RVTEST_IO_WRITE_STR(x,y)
#define RVTEST_IO_CHECK()
#define RV_COMPLIANCE_HALT sw x0, -36(x0)
#define RV_COMPLIANCE_CODE_END
#define RV_COMPLIANCE_DATA_BEGIN
#define RV_COMPLIANCE_DATA_END
#define RVTEST_IO_ASSERT_GPR_EQ(a,b,c) sw b, -32(x0)
